---
name: Python application

on:
    push:
        branches: [main, nightly]
        paths:
            - agilerl/**
            - pyproject.toml
    pull_request:
        branches: [main, nightly]
        paths:
            - agilerl/**
            - pyproject.toml

permissions:
    contents: read

jobs:
    build:
        runs-on: gha-runner-scale-set
        container:
            image: pytorch/pytorch:2.7.1-cuda12.6-cudnn9-devel
            options: --user root
        # todo: test on different python versions!
        # strategy:
        #     matrix:
        #         python-version: ["3.10", "3.11", "3.12"]
        steps:
            - uses: actions/checkout@v4
            # - name: Set up Python 3.11
            #   uses: actions/setup-python@v4
            #   with:
            #       python-version: '3.11'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

                  # Use uv for faster downloads
                  pip install uv
                  uv pip install --system ruff pytest pytest-cov black codespell yamlfmt isort pyupgrade
                  uv pip install --system -e .[llm]
            - name: Run black
              run: |
                  black .
            - name: Spellcheck with codespell
              run: |
                  codespell --skip=*.css,*.js,*.map,*.scss,*.svg --ignore-words-list=magent,pres,roate
            - name: Lint with ruff
              run: |
                  ruff check .
            - name: Run pyupgrade
              run: |
                  pyupgrade --py38-plus
            - name: Test with pytest
              run: |
                  pytest --exitfirst --cov=agilerl --cov-report=xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
