---
name: Python application

on:
    push:
        branches: [main, nightly]
        paths:
            - agilerl/**
    pull_request:
        branches: [main, nightly]
        paths:
            - agilerl/**

permissions:
    contents: read

jobs:
    build:
        runs-on: gha-runner-scale-set
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.10', '3.11', '3.12', '3.13']

        # Use the same high-performance GPU image for all versions
        container:
            image: pytorch/pytorch:2.7.1-cuda12.6-cudnn9-devel
            options: --user root

        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  uv venv .venv --python ${{ matrix.python-version }}
                  uv pip install ruff pytest pytest-cov black codespell yamlfmt isort pyupgrade
                  uv sync --locked --all-groups --extra all

            - name: Run black
              run: |
                  black .
            - name: Spellcheck with codespell
              run: |
                  codespell --skip=*.css,*.js,*.map,*.scss,*.svg --ignore-words-list=magent,pres,roate
            - name: Lint with ruff
              run: |
                  ruff check .
            - name: Run pyupgrade
              run: |
                  pyupgrade --py38-plus
            - name: Test with pytest
              run: |
                  uv run pytest --exitfirst --cov=agilerl --cov-report=xml
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
